name = input('What is your name? ')
print('Nice to meet you ' + name + ', my name is Chatbot.')
age = input('How old are you? ')
print('Wow, ' + age + ' years old! I was born today.')
feeling = input('How are you feeling today? ')
print('Glad to hear you are feeling ' + feeling.lower() + '. That is wonderful to hear!')
day = input('What is your favorite day of the week? ')
print('Wow! ' + day.title() + ' is my favorite day too!')