name = input('What is your name? ')
print('UGH, I HATE YOU ' + name.upper() + '.')
color = input('What is your favorite color? ')
print('UGH, I HATE ' + color.upper() + ', THERE ARE SO MANY BETTER COLORS.')
subject = input('What is your favorite subject in school? ')
print('UGH, I HATE ' + subject.upper() + '. I HATE EVERYTHING!')
chatbot = input('What is your favorite chatbot? ')
print('UGH, I HATE ' + chatbot.upper() + "!")